num_1 = int(input("Ingrese un numero: "))
num_2 = int(input("Ingrese un numero: "))
suma = num_1 + num_2
multiplicacion = num_1 * num_2
resta = num_1 - num_2
division = num_1/num_2
print(f"{num_1} + {num_2} = {suma}")
print(f"{num_1} - {num_2} = {resta}")
print(f"{num_1} x {num_2} = {multiplicacion}")
print(f"{num_1} / {num_2} = {division}")
